repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 44afb68a9695d04030edc5cdc5a4fc4f17e4f9e2  # frozen: v0.910
    hooks:
    -   id: mypy
        exclude: docs/conf.py$|tasks.py$
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: d296b6df65ac00bc5e828e792120b73b51dc2a5e  # frozen: v3.0.0a3
    hooks:
    -   id: pylint
        exclude: docs/conf.py$
        args: ["--disable=E0401"]
-   repo: https://github.com/psf/black
    rev: 93c10bf9ebccf8d7cc686b0b9579f2e5e41c5328  # frozen: 21.6b0
    hooks:
    -   id: black
        exclude: docs/conf.py$
-   repo: https://github.com/asottile/blacken-docs
    rev: 11c213590abfc28ab52587efc9c81a7076dd17c9  # frozen: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.5b2]
-   repo: https://github.com/PyCQA/isort
    rev: a6222a8a125ec719724e628a5d3d0d5c60923281  # frozen: 5.8.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        exclude: docs/conf.py$
-   repo: https://github.com/PyCQA/flake8
    rev: dcd740bc0ebaf2b3d43e59a0060d157c97de13f3  # frozen: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [pep8-naming]
        exclude: docs/conf.py$
-   repo: https://github.com/PyCQA/doc8
    rev: 1fc3c214b267d57188658c17b60cfed0752deb2f  # frozen: 0.9.0a1
    hooks:
    -   id: doc8
        args: ["--max-line-length", "88"]
-   repo: https://github.com/PyCQA/bandit
    rev: 9b62635bd078b7f51e98b5300c6a6352f698d78a  # frozen: 1.7.0
    hooks:
    -   id: bandit
        exclude: tests/.*
-   repo: https://github.com/PyCQA/pydocstyle
    rev: eade6b5b4f083e087e329cc8a9f02bb372a03100  # frozen: 6.1.1
    hooks:
    -   id: pydocstyle
        files: \.py$
        exclude: docs/conf.py$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/econchick/interrogate
    rev: a63b8607b1cf0ef2885a7c45488f40f450a1dcab  # frozen: 1.4.0
    hooks:
    -   id: interrogate
        exclude: tests/.*py$
-   repo: https://github.com/econchick/interrogate
    rev: a63b8607b1cf0ef2885a7c45488f40f450a1dcab  # frozen: 1.4.0
    hooks:
    -   id: interrogate
        name: interrogate tests
        args: ["--fail-under", "100", "--whitelist-regex", "test_.*"]
        files: tests/.*py$
