update: all
pin: False
search: False
requirements:
    - requirements.txt:
        # Pin, but only update insecure.
        # Should keep us from being pinned to an
        # insecure package, but not spam PRs
        pin: True
        update: insecure
    - requirements/requirements_loose.txt:
        # Don't pin - update everything if possible
        # ie: Prompt us to upgrade major versions,
        # if we're pinned to the previous major
        pin: False
