update: all
pin: False
search: False
requirements:
    - requirements.txt:
        # Pin, but only update insecure.
        # Should keep us from being pinned to an
        # insecure package, but not spam PRs
        pin: True
        update: insecure
