language: python
python:
    - "3.7"
dist: xenial
sudo: required
before_script:
    - pip install tox-travis python-coveralls
install: 
    - "pip install -r requirements/requirements_tests.txt -r requirements.txt"
    - "python setup.py install"
script: 
    - tox
    - coverage run --source {{ cookiecutter.slug_name }} -m py.test
after_success:
    - coveralls
