language: python
python:
    - "3.7"
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"
before_script:
    - pip install tox-travis python-coveralls
install: 
    - "pip install -r requirements/requirements_test.txt -r requirements.txt"
    - "python setup.py install"
script: 
    - tox
    - coverage run --source {{ cookiecutter.slug_name }} -m py.test
after_success:
    - coveralls
