language: python
python:
    - "3.8"
dist: xenial
sudo: required
before_script:
    - pip install -r requirements/requirements_ci.txt
install:
    - "pip install -r requirements.txt -r requirements/requirements_tests.txt"
    - "python setup.py install"
script:
    - tox
after_success:
    - coveralls
