language: python
python:
    - "3.5"
before_script:
    - pip install python-coveralls
install: 
    - "pip install -r requirements_dev.txt"
    - "python setup.py install"
script: 
    - coverage run --source {{ cookiecutter.slug_name }} -m py.test 
after_success:
    - flake8 --exit-zero
    - isort -rc --diff -c {{ cookiecutter.slug_name }}
    - bandit -r {{ cookiecutter.slug_name }}
    - coverage report
    - coveralls
