[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
not_skip = "__init__.py"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.check-manifest]
ignore = [
    ".editorconfig",
    "tox.ini",
    "requirements.txt",
    "requirements*",
    "docs*",
    ".github*",
    "tests*",
    ".pyup.yml",
    ".readthedocs.yml",
    ".pylintrc"
]
