[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.check-manifest]
ignore = [
    "*__pycache__",
    "*.py[cod]",
    "*$py.class",
    ".editorconfig",
    "tox.ini",
    "requirements.txt",
    "docs*",
    ".github*",
    "tests*",
    ".pyup.yml",
    ".readthedocs.yml",
    ".pylintrc"
]

[tool.coverage.run]
source = ["{{ cookiecutter.module_name }}"]

[tool.coverage.report]
fail_under = 80

[tool.coverage.paths]
source = [
   "src",
   ".tox/*/site-packages"
]
