{% raw -%}
---
name: CI

on:
  push:
    branches: ["{{ cookiecutter.github_default_branch_name }}"]
  pull_request:
    branches: ["{{ cookiecutter.github_default_branch_name }}"]
  workflow_dispatch:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "excitedleigh/setup-nox@v2.0.0"
      - run: |
          python -m pip install coverage poetry
          poetry install
          poetry run inv run.tests --no-autoformat
      - name: "Generate coverage XML"
        run: "poetry run coverage xml"
      - name: "Upload Coverage to CodeCov"
        uses: "codecov/codecov-action@v1"
{%- endraw %}
