---
name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: "Test the cookiecutter"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel cookiecutter tox
      - name: "Create repo and test"
        env: 
          TOX_SKIP_ENV: "py3[76]" # Skip other pythons to avoid having to install pyenv
        run: |
          set -xe
          cookiecutter . --no-input
          cd MyProject
          git init
          git add {.[!.]*,*}
          tox
