---
name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    name: "Test the cookiecutter"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel cookiecutter poetry
      - name: "Create repo and test"
        run: |
          set -xe
          cookiecutter . --no-input
          cd My-Project
          git init
          git add {.[!.]*,*}
          poetry install -E docs -E tests
          git add poetry.lock
          poetry run inv test
          poetry run inv build
          poetry run inv build.dists
          poetry run inv build.docs
          poetry run inv build.coverage-report
          poetry run inv build.zipapp
          poetry run inv clean
          poetry run inv check.todos
      - name: "Build test example"
        run: |
          echo -e "bnb-cookiecutter-example-test\n\n\n\n\n\n\n\nbnbalsamo\n\n\n\n\n" | cookiecutter .
      - name: Push to test example repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "bnb-cookiecutter-example-test"
          destination-github-username: "bnbalsamo"
          destination-repository-name: "bnb-cookiecutter-example-test"
          target-branch: "main"
          user-email: "Brian@BrianBalsamo.com"
